site_name: Material Static Website for Course Notes
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      clickable_checkbox: true
theme:
  name: material
  palette:
    scheme: slate
  features: 
    - content.code.copy
    - content.code.annotations